### PR TITLE
Formatter factory (can register formatters)

### PR DESCRIPTION
**Pull request by ognen**
Hello,

I've made a small enhancement to httpriot: the ability to register custom formatters. 

The idea is to be able to request resources that will turn up to be images using the [HRRestModel getPath] method.

### CODE REVIEW

**Comment by caged** [comment]
Hey, sorry for getting back to you so late.  I really like these changes, but I'm unfortunately not doing much iPhone dev these days and haven't had time to maintain this project.  Would you be interested in taking it over?

**Comment by ognen** [comment]
Hello,

Yes I would be interested in taking over!  I do ios work almost 100% of the time and since we are already using httpriot in our projects it wouldn't be too much hassle...

**Comment by caged** [comment]
Awesome, thanks!  I really hated to see it rot in obscurity.  We can do this one of two ways, I can point people to your fork or I can add you as a collaborator on this project.

**Comment by ognen** [comment]
What's easy for you? Apart from the source tree are there any other resources to be managed (issue lists, etc?). If not, probably the easiest way to go is to point to my branch.

**Comment by caged** [comment]
I just pointed people to your repo.  Let me know if you have any questions.  I'd really like to see the project succeed.  Thanks!

**Pull request closed without merging**
